### ISSUE TITLE
error training test

### ISSUE THREAD

**Issue by AGoodWolf** [mingyuliutw/UNIT#6]
thank you for the opening-source code and I follow the instruction in  `readme` and run into this error:

> Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main(sys.argv)
  File "train.py", line 182, in main
    for it, (images_a, images_b, images_a2, images_b2) in enumerate(itertools.izip(train_loader_a, train_loader_b, train_loader_a2, train_loader_b2)):
  File "/home/lz/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 179, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/lz/UNIT-master/src/datasets/dataset_image.py", line 37, in __getitem__
    crop_img = self._load_one_image(self.images[index])
  File "/home/lz/UNIT-master/src/datasets/dataset_image.py", line 62, in _load_one_image
    crop_img = img[y_offset:(y_offset + self.image_size), x_offset:(x_offset + self.image_size), :]
TypeError: only integer scalar arrays can be converted to a scalar index

can you hint me where i can make this mistake ,thanks a lot

**Comment by mingyuliutw** [comment]
The code has been updated.
